#!/bin/bash

echo "🚀 Starting All OnlyOne Services (Jaeger + K6 + Grafana)..."
echo "========================================================"

# 모든 서비스 시작
docker-compose -f docker-compose-all.yml up -d

echo "⏳ Waiting for services to start up (30 seconds)..."
sleep 30

echo ""
echo "✅ Service Status:"
echo "================="
docker-compose -f docker-compose-all.yml ps

echo ""
echo "🌐 Service Access URLs:"
echo "======================="
echo "📊 Grafana (Dashboard):     http://localhost:3000 (admin/admin)"
echo "🔍 Prometheus (Metrics):    http://localhost:9090"  
echo "🔎 Jaeger (Tracing):        http://localhost:16686"
echo "📈 InfluxDB (K6 Metrics):   http://localhost:8086"
echo "💾 MySQL (Database):        localhost:3306"
echo "🗂️  Redis (Cache):           localhost:6379"
echo ""
echo "🛠️  Development Tools (--profile dev):"
echo "📊 phpMyAdmin:               http://localhost:8090"
echo "🗂️  Redis Commander:         http://localhost:8091"
echo ""
echo "🎯 Spring Boot Endpoints:"
echo "=========================="
echo "📡 Metrics:                 http://localhost:8080/actuator/prometheus"
echo "💓 Health:                  http://localhost:8080/actuator/health"
echo "📊 Metrics JSON:            http://localhost:8080/actuator/metrics"
echo "🔍 Jaeger Traces:           http://localhost:8080/actuator/traces"
echo ""
echo "🔥 Load Testing Commands:"
echo "========================="
echo "# Basic endpoint test:"
echo "docker-compose -f docker-compose-all.yml --profile load-test up k6"
echo ""
echo "# Heavy load test (10K users):"
echo "docker run --rm --network onlyone-back_app-network \\"
echo "  -v \$(pwd)/k6-scripts:/scripts \\"
echo "  grafana/k6:latest run \\"
echo "  --out influxdb=http://influxdb:8086/k6 \\"
echo "  /scripts/notification-endpoints-test.js"
echo ""
echo "# Development tools:"
echo "docker-compose -f docker-compose-all.yml --profile dev up -d phpmyadmin redis-commander"
echo ""
echo "🎯 Next Steps:"
echo "============="
echo "1. Start Spring Boot: ./gradlew bootRun"
echo "2. Import Grafana Dashboard: grafana-hikaricp-dashboard.json"
echo "3. Run Load Test: ./run-k6-test.sh"
echo "4. Check Jaeger Traces for 37s issue"
echo ""
echo "🏆 All services are ready!"