version: '3.8'

services:
  core:
    image: goormonlyone/onlyone-hub:latest
    container_name: back-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: password
    ports:
      - 8080:8080
    volumes:
      - ./src/main/resources:/config
    networks:
      - goormonlyone-network

  redis:
    image: redis:latest
    container_name: redis-server
    environment:
      - REDIS_PASSWORD=password
    ports:
      - 6379:6379
    command: [redis-server, --requirepass, password]
    networks:
      - doubleone-network
networks:
  doubleone-network:
    driver: bridge