FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

RUN go install go.k6.io/xk6/cmd/xk6@latest

RUN xk6 build \
    --with github.com/phymbert/xk6-sse@latest \
    --output /k6

FROM alpine:3.21
COPY --from=builder /k6 /usr/bin/k6

ENTRYPOINT ["k6"]
