name:  CI/CD with Docker

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Make application-prod.yml
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml

      - name: Setup Firebase service key
          run: |
            mkdir -p src/main/resources/firebase
            echo ${{ secrets.FIREBASE_ACCOUNT }} | base64 -d > src/main/resources/firebase/service-account.json

      - name: Build with Gradle
        run: |
          cd ./
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Server build & push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            echo "${{ secrets.DOCKER_COMPOSE }}" | sudo tee ./docker-compose.yml
            sudo docker ps -q | xargs -r sudo docker stop && sudo docker ps -aq | xargs -r sudo docker rm
            sudo docker compose -f ./docker-compose.yml down --rmi all
            sudo docker pull ${{ secrets.DOCKER_REPO}}:latest
            sudo docker compose -f ./docker-compose.yml up -d
